// import './js/recipe';
import './js/switcher';
// import './js/scroll-up';
import './js/slider';
import './js/header-burger';
// import './js/extrafilters';
import './js/theme-switcher';
// import './js/home_categories-api';
import './js/create-order.js';
import './js/popular-recipes';
